# Generated by Django 2.2.3 on 2021-02-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(blank=True, max_length=2, null=True, verbose_name='Position')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='Back Number')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('barth', models.CharField(blank=True, max_length=100, verbose_name='Barth')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Player Directory',
            },
        ),
    ]
